In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append(r'G:\00temp\code\highway-env-1.5')
sys.path.append(r'G:\00temp\code\highway-env-1.5')
import numpy as np
import gym
from gym.wrappers import RecordVideo
from stable_baselines3 import DQN

In [31]:
import numpy.matlib
import pandas as pd

In [32]:
a = pd.DataFrame(np.random.randint(0,100,size=(2, 3)))

In [64]:
x = np.random.random((3, 2))
y = np.random.random((4, 2))
x, x[0, :].argmax()

(array([[0.25849456, 0.01383418],
        [0.42128215, 0.71527419],
        [0.72413051, 0.98323044]]),
 0)

In [65]:
import highway_env
env = gym.make("highway-bs-v0")


f:\Miniconda3\lib\site-packages\gym\envs\registration.py:216: UserWarning: WARN: Overriding environment highway-bs-v0
  logger.warn("Overriding environment {}".format(id))


In [105]:
from highway_env.vehicle.objects import *

road = env.road
road.objects
Obstacle(road, [100, 100]).lane_index

('0', '1', 2)

In [88]:
env2 = gym.make("highway-v0")

In [97]:
env2.road.vehicles[1].lane_index

('0', '1', 3)

In [120]:
''.startswith()

[1, 2, 3]

In [119]:
b = a[0]
b = b + 1
a, b

(array([[1.95952798, 1.20503197, 1.90531319],
        [0.61638572, 0.07083094, 0.69071648]]),
 array([2.95952798, 2.20503197, 2.90531319]))

In [ ]:
obs = env.reset()

In [ ]:
print(env.action_space)  # 输出动作信息
print(env.action_space.n)  # 输出动作个数
print()  # 查看状态空间
print(env.observation_space)  # 查看状态空间
print(env.observation_space.shape[0])  # 输出状态个数
# obs

In [ ]:
env2.action_space.sample(), env2.action_space.n

In [ ]:
env.reset()
_, _, over, _ = env.step(env.action_space.sample())

In [ ]:
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()